apiVersion: v1
kind: Service
metadata:
  labels:
    component: api
  name: api
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: api
  selector:
    app: todo
    component: api
  type: ClusterIP
# TODO Erreur ici pour que ça fonctionne